apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring
  name: spring-producer-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - image: ksreddy4599/swe_prod:latest
        name: spring